<div class=" w-full bg-white">
    <!-- Sticky top border -->
    <div class="sticky top-0 w-full h-10 bg-green z-30"></div>
  

    <div class="border-3 border-blue w-2/3 mx-auto">
    <p class="m-10">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed venenatis mi eu orci aliquet venenatis. Nunc velit dui, cursus quis laoreet nec, eleifend sit amet ante. Duis sed nibh sodales sem vehicula suscipit. Proin fermentum a tortor imperdiet scelerisque. Sed metus elit, aliquam quis ligula vel, gravida pharetra tortor. Aenean lobortis risus ut neque porttitor, sit amet ornare eros hendrerit. Suspendisse et consequat dolor. Suspendisse facilisis dignissim magna, vel ullamcorper mi semper at. Donec elementum viverra diam, vitae pellentesque ligula dignissim porta. In bibendum enim magna, a consectetur dolor bibendum sit amet. Nulla ut pulvinar enim, quis rutrum felis. Aliquam erat volutpat. Curabitur tempus tempus nulla, ultrices porttitor neque pulvinar ac.</p>
    <p class="m-10">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed venenatis mi eu orci aliquet venenatis. Nunc velit dui, cursus quis laoreet nec, eleifend sit amet ante. Duis sed nibh sodales sem vehicula suscipit. Proin fermentum a tortor imperdiet scelerisque. Sed metus elit, aliquam quis ligula vel, gravida pharetra tortor. Aenean lobortis risus ut neque porttitor, sit amet ornare eros hendrerit. Suspendisse et consequat dolor. Suspendisse facilisis dignissim magna, vel ullamcorper mi semper at. Donec elementum viverra diam, vitae pellentesque ligula dignissim porta. In bibendum enim magna, a consectetur dolor bibendum sit amet. Nulla ut pulvinar enim, quis rutrum felis. Aliquam erat volutpat. Curabitur tempus tempus nulla, ultrices porttitor neque pulvinar ac.</p>
    <p class="m-10">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed venenatis mi eu orci aliquet venenatis. Nunc velit dui, cursus quis laoreet nec, eleifend sit amet ante. Duis sed nibh sodales sem vehicula suscipit. Proin fermentum a tortor imperdiet scelerisque. Sed metus elit, aliquam quis ligula vel, gravida pharetra tortor. Aenean lobortis risus ut neque porttitor, sit amet ornare eros hendrerit. Suspendisse et consequat dolor. Suspendisse facilisis dignissim magna, vel ullamcorper mi semper at. Donec elementum viverra diam, vitae pellentesque ligula dignissim porta. In bibendum enim magna, a consectetur dolor bibendum sit amet. Nulla ut pulvinar enim, quis rutrum felis. Aliquam erat volutpat. Curabitur tempus tempus nulla, ultrices porttitor neque pulvinar ac.</p>
    <p class="m-10">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed venenatis mi eu orci aliquet venenatis. Nunc velit dui, cursus quis laoreet nec, eleifend sit amet ante. Duis sed nibh sodales sem vehicula suscipit. Proin fermentum a tortor imperdiet scelerisque. Sed metus elit, aliquam quis ligula vel, gravida pharetra tortor. Aenean lobortis risus ut neque porttitor, sit amet ornare eros hendrerit. Suspendisse et consequat dolor. Suspendisse facilisis dignissim magna, vel ullamcorper mi semper at. Donec elementum viverra diam, vitae pellentesque ligula dignissim porta. In bibendum enim magna, a consectetur dolor bibendum sit amet. Nulla ut pulvinar enim, quis rutrum felis. Aliquam erat volutpat. Curabitur tempus tempus nulla, ultrices porttitor neque pulvinar ac.</p>
    <p class="m-10">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed venenatis mi eu orci aliquet venenatis. Nunc velit dui, cursus quis laoreet nec, eleifend sit amet ante. Duis sed nibh sodales sem vehicula suscipit. Proin fermentum a tortor imperdiet scelerisque. Sed metus elit, aliquam quis ligula vel, gravida pharetra tortor. Aenean lobortis risus ut neque porttitor, sit amet ornare eros hendrerit. Suspendisse et consequat dolor. Suspendisse facilisis dignissim magna, vel ullamcorper mi semper at. Donec elementum viverra diam, vitae pellentesque ligula dignissim porta. In bibendum enim magna, a consectetur dolor bibendum sit amet. Nulla ut pulvinar enim, quis rutrum felis. Aliquam erat volutpat. Curabitur tempus tempus nulla, ultrices porttitor neque pulvinar ac.</p>

    <p class="m-10">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed venenatis mi eu orci aliquet venenatis. Nunc velit dui, cursus quis laoreet nec, eleifend sit amet ante. Duis sed nibh sodales sem vehicula suscipit. Proin fermentum a tortor imperdiet scelerisque. Sed metus elit, aliquam quis ligula vel, gravida pharetra tortor. Aenean lobortis risus ut neque porttitor, sit amet ornare eros hendrerit. Suspendisse et consequat dolor. Suspendisse facilisis dignissim magna, vel ullamcorper mi semper at. Donec elementum viverra diam, vitae pellentesque ligula dignissim porta. In bibendum enim magna, a consectetur dolor bibendum sit amet. Nulla ut pulvinar enim, quis rutrum felis. Aliquam erat volutpat. Curabitur tempus tempus nulla, ultrices porttitor neque pulvinar ac.</p>
    <p class="m-10">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed venenatis mi eu orci aliquet venenatis. Nunc velit dui, cursus quis laoreet nec, eleifend sit amet ante. Duis sed nibh sodales sem vehicula suscipit. Proin fermentum a tortor imperdiet scelerisque. Sed metus elit, aliquam quis ligula vel, gravida pharetra tortor. Aenean lobortis risus ut neque porttitor, sit amet ornare eros hendrerit. Suspendisse et consequat dolor. Suspendisse facilisis dignissim magna, vel ullamcorper mi semper at. Donec elementum viverra diam, vitae pellentesque ligula dignissim porta. In bibendum enim magna, a consectetur dolor bibendum sit amet. Nulla ut pulvinar enim, quis rutrum felis. Aliquam erat volutpat. Curabitur tempus tempus nulla, ultrices porttitor neque pulvinar ac.</p>
    <p class="m-10">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed venenatis mi eu orci aliquet venenatis. Nunc velit dui, cursus quis laoreet nec, eleifend sit amet ante. Duis sed nibh sodales sem vehicula suscipit. Proin fermentum a tortor imperdiet scelerisque. Sed metus elit, aliquam quis ligula vel, gravida pharetra tortor. Aenean lobortis risus ut neque porttitor, sit amet ornare eros hendrerit. Suspendisse et consequat dolor. Suspendisse facilisis dignissim magna, vel ullamcorper mi semper at. Donec elementum viverra diam, vitae pellentesque ligula dignissim porta. In bibendum enim magna, a consectetur dolor bibendum sit amet. Nulla ut pulvinar enim, quis rutrum felis. Aliquam erat volutpat. Curabitur tempus tempus nulla, ultrices porttitor neque pulvinar ac.</p>
    </div>
<div class="sticky bottom-0 w-full bg-blue-950 h-10 z-10"></div>
</div>